# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: namatias <namatias@42sp.org.br>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/07/22 19:25:38 by namatias          #+#    #+#              #
#    Updated: 2025/12/09 13:33:41 by namatias         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

################################################################################
#                            Variaveis / Variables                             #
################################################################################

NAME = libft.a

CC = cc
CFLAGS = -Wall -Wextra -Werror

FILESC = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c \
		 ft_toupper.c ft_tolower.c ft_strlen.c ft_strlcpy.c ft_strlcat.c \
		 ft_strnstr.c ft_strchr.c ft_strrchr.c ft_strncmp.c ft_strdup.c \
		 ft_calloc.c ft_bzero.c ft_memset.c ft_memcpy.c ft_memmove.c \
		 ft_memchr.c ft_memcmp.c ft_atoi.c ft_substr.c ft_strtrim.c \
		 ft_split.c ft_itoa.c ft_strmapi.c ft_putchar_fd.c ft_putendl_fd.c \
		 ft_putnbr_fd.c ft_putstr_fd.c ft_striteri.c ft_strjoin.c ft_putnbr.c

FILESO = $(FILESC:.c=.o)

################################################################################
#                             Funções / Functions                              #
################################################################################

all: $(NAME)

$(NAME): $(FILESO)
	@ar rcs $(NAME) $(FILESO)

%.o : %.c
	@$(CC) $(CFLAGS) -c $< -o $@

clean:
	@rm -f $(FILESO)

fclean: clean
	@rm -f $(NAME)

re:
	@$(MAKE) fclean 
	@$(MAKE) all

.PHONY: all clean fclean re
